### ISSUE TITLE
List of important missing aircraft EFF1510z 2023/12/31

### ISSUE THREAD

**Issue by becas22** [vatsimnetwork/euroscope-performance-data#3]
A359
A35K
A388
B788
B789
B78X
BCS1

**Comment by becas22** [comment]
A400
C17
F16
F18

**Comment by kusterjs** [comment]
done #6

**Comment by becas22** [comment]
@kusterjs Erik did not add all the types missing. The ones he added I removed from the list and updated the issue name with the new effective date

**Comment by kusterjs** [comment]
> @kusterjs Erik did not add all the types missing. The ones he added I removed from the list and updated the issue name with the new effective date

He did, please check the latest file.
